name: Makefile CI

on:
  workflow_dispatch:
    null

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install libext2fs-dev
          
    - name: configure
      run: ./configure LDFLAGS=-Wl,--allow-multiple-definition

    - name: Run compilation and check
      run: make check

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
          #name: dist-without-markdown
          path: |
            defrag
            e2defrag
            README
            NEWS
            AUTHORS
          if-no-files-found: error
