name: Makefile CI

on:
  workflow_dispatch:
    inputs:
        ncursesw_typ:
            type: boolean
            description: 'Target OS uses ncursesw other than ncurses'
            default: true
        no_tinfo:
            type: boolean
            description: 'Ncurses(w) of the target OS does not split out libtinfo'
            default: true
#env: 
#  ncurses_url: https://mirrors.dotsrc.org/gnu/ncurses/ncurses-6.6.tar.gz

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
          sudo apt-get update
          apt-get --no-act install ncurses-base & exit 1
          sudo apt-get install libext2fs-dev
          #sudo apt-get install libncurses-dev
          #apt list --installed

          echo "ncname=nc-$(apt-cache policy ncurses | awk '/Candidate:/ {print $2}')" >> $GITHUB_ENV
          #echo "ncname=${ncurses_url##*/}" >> $GITHUB_ENV

    - name: Patch configure to switch to ncurcesw
      if: inputs.ncursesw_typ
      run: sed -i "s/ncurses/ncursesw/" ./configure

    - name: Cache compiled ncurses lib
      if: inputs.no_tinfo
      id: cache
      uses: actions/cache@v6
      with:
          path: ncurse
          key: ${{env.ncname}}
      
    - name: Compile ncurses separately to fulfill the requirement
      if: ${{ inputs.no_tinfo && steps.cache.outputs.cache-hit != 'true' }}
      run: |
          sudo apt-get -f --force-yes remove libncurses-dev
          #wget -q -O nc.tar.gz ${{env.ncurses_url}}
          #tar -xf nc.tar.gz
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          apt-get source ncurses
          mv ncurses* ncurse
          cd ncurse/
          ./configure --prefix=$PWD/dist --without-cxx --without-cxx-binding --without-ada --without-manpages --enable-overwrite --without-debug --without-tests --with-shared --without-tests --without-progs $([ "${{inputs.ncursesw_typ}}" = true ] && echo --enable-widec || echo --disable-widec)
          make && make install 
          ls -R dist
          
    - name: configure
      run: |
          cf="-I." # overstress the priority of header files in the source directory to ensure their precedence, to avoid conflicts caused by other config.h
          lf=-Wl,--allow-multiple-definition,-M
          if [ "${{inputs.no_tinfo}}" = true ]; then
              cf=${cf}" -I ./ncurse/dist/include"
              lf=${lf},-L,./ncurse/dist/lib
          fi
          ./configure CFLAGS="$cf" LDFLAGS="$lf"

    - name: Run compilation and check
      run: |
          make check
          ldd e2defrag

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
          #name: dist-without-markdown
          path: |
            defrag
            e2defrag
            README
            NEWS
            AUTHORS
          if-no-files-found: error
