name: Makefile CI

on:
  workflow_dispatch:
    inputs:
        ncursesw_typ:
            type: boolean
            description: 'Target OS uses ncursesw other than ncurses'
            default: true
        no_tinfo:
            type: boolean
            description: 'Ncurses(w) of the target OS does not split out libtinfo'
            default: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install libext2fs-dev
          #sudo apt-get install libncurses-dev

    - name: Patch configure to switch to ncurcesw
      if: inputs.ncursesw_typ
      run: sed -i "s/ncurses/ncursesw/" ./configure
      
    - name: Compile ncurses separately to fulfill the requirement
      if: inputs.no_tinfo
      run: |
          wget -O nc.tar.gz http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.6.tar.gz
          tar -vxf nc.tar.gz
          mv ncurses* ncurse
          cd ncurse/
          ./configure --prefix=$PWD --without-cxx --without-cxx-binding --without-ada --without-manpages --enable-overwrite --without-debug --without-tests --with-shared --without-tests --without-progs $([ "${{inputs.ncursesw_typ}}" = true ] && echo --enable-widec || echo --disable-widec)
          make # && make install 
          ls
          
    - name: configure
      run: |
          cf=""
          lf=-Wl,--allow-multiple-definition
          if [ "${{inputs.ncursesw_typ}}" = true ]; then
              cf=${cf}" -I ncurse/include"
              lf=${lf},-L,ncurse/lib
          fi
          ./configure CFLAGS=$cf LDFLAGS=$lf

    - name: Run compilation and check
      run: |
          make check
          ldd e2defrag

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
          #name: dist-without-markdown
          path: |
            defrag
            e2defrag
            README
            NEWS
            AUTHORS
          if-no-files-found: error
